# -*- mode: ruby -*-

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "debian/bookworm64"

  # Disable automatic box update checking.
  config.vm.box_check_update = false

  # Change the size of the existing disk. Be sure to install the external
  # vagrant plugin https://github.com/sprotheroe/vagrant-disksize.
  # config.disksize.size = "64GB"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.56.20"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network", type: "dhcp"

  # Keep the default Vagrant share directory (for Ansible provision).
  # config.vm.synced_folder ".", "/vagrant", disabled: true

  # The hostname the machine should have.
  config.vm.hostname = "odoo-bookworm"

  # VirtualBox-specific configurations.
  config.vm.provider "virtualbox" do |vbox|
    vbox.name = "Odoo-bookworm"
    vbox.cpus = 2
    vbox.memory = 2048
    vbox.check_guest_additions = false
    vbox.gui = false
    vbox.customize ["modifyvm", :id, "--vram", "32"]
  end

  # Extend partition size with a shell script to fill available space.
  # config.vm.provision "shell", inline: <<-SCRIPT
  #   growpart /dev/sda 1
  #   resize2fs /dev/sda1
  # SCRIPT

  # Run Ansible from the Vagrant VM
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbooks/ansible.yaml"
    ansible.compatibility_mode = "2.0"
    ansible.verbose = true
  end

end
