---
- name: System config
  hosts: all
  become: yes

  tasks:
    - name: Disable SSH HashKnownHosts
      ansible.builtin.template:
        src: ../templates/ssh_config.j2
        dest: /etc/ssh/ssh_config.d/10-HashKnownHosts.conf
        mode: "0644"

    - name: Allow SSH password authentication
      ansible.builtin.template:
        src: ../templates/sshd_config.j2
        dest: /etc/ssh/sshd_config.d/10-PasswordAuthentication.conf
        mode: "0644"

    - name: Reset vagrant user password
      ansible.builtin.user:
        name: vagrant
        password: "{{ 'vagrant' | password_hash('sha512') }}"

    - name: Set timezone
      community.general.timezone:
        name: Europe/Rome

    - name: Add bash aliases
      ansible.builtin.template:
        src: ../templates/bash_aliases.j2
        dest: /home/vagrant/.bash_aliases
        owner: vagrant
        group: vagrant
        mode: "0644"
