# -*- mode: ruby -*-

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/focal64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = false

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.56.20"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  config.vm.network "public_network", type: "dhcp"

  # Disable the default share of the current code directory.
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # The hostname the machine should have.
  config.vm.hostname = "odoo-dev2020"

  # Disks
  # [!] requires environment variable VAGRANT_EXPERIMENTAL="disks"
  config.vm.disk :disk, name: "dev2020", size: "64GB", disk_ext: "vdi"

  # VirtualBox
  config.vm.provider "virtualbox" do |vbox|
    vbox.name = "Odoo-dev2020"
    vbox.cpus = 2
    vbox.memory = 2048
    vbox.gui = false
    vbox.check_guest_additions = false
  end

  # Install nginx and python2 with inline script
  config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y nginx python2
  SHELL

end
